"""base struct

Revision ID: b81471a09959
Revises: 
Create Date: 2026-03-15 03:02:13.104983

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'b81471a09959'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
