"""upload banner

Revision ID: 41bf0c75c003
Revises: 2add9b64a372
Create Date: 2026-03-15 04:20:09.518308

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '41bf0c75c003'
down_revision: Union[str, Sequence[str], None] = '2add9b64a372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
