"""activities

Revision ID: 52d7e0f8d7e0
Revises: a1b2c3d4e5f6
Create Date: 2026-03-15 16:35:07.046988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d7e0f8d7e0'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('game_created', 'favorite_added', 'favorite_removed', name='activityactiontype', native_enum=False, create_constraint=True),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_activity_created_at'))

    with op.batch_alter_table('activity_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_vote', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('action_type',
               existing_type=sa.Enum('game_created', 'favorite_added', 'favorite_removed', name='activityactiontype', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
