"""comments

Revision ID: 60656d72fafa
Revises: 044f1422535e
Create Date: 2026-03-15 06:39:22.361738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60656d72fafa'
down_revision: Union[str, Sequence[str], None] = '044f1422535e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_comment_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_comment_vote', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
