"""update game card

Revision ID: 7ef9063a1a10
Revises: a579c82dfcba
Create Date: 2026-03-15 05:10:22.339327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef9063a1a10'
down_revision: Union[str, Sequence[str], None] = 'a579c82dfcba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('developers',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('publishers',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.alter_column('publishers',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('developers',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('genres',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
