"""refactor

Revision ID: 33af5c966168
Revises: 60656d72fafa
Create Date: 2026-03-15 16:24:02.144795

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '33af5c966168'
down_revision: Union[str, Sequence[str], None] = '60656d72fafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
