"""rename steam_url to steam_app_id

Revision ID: 5b88a21a89fa
Revises: 833905f4189e
Create Date: 2026-03-15 03:30:37.030480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b88a21a89fa'
down_revision: Union[str, Sequence[str], None] = '833905f4189e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_app_id', sa.String(length=20), nullable=True))
        batch_op.drop_column('steam_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('steam_app_id')

    # ### end Alembic commands ###
