from enum import StrEnum


BACKLOG_GAME_STATE = 'backlog'
IN_PROGRESS_GAME_STATE = 'in_progress'
COMPLETED_GAME_STATE = 'completed'
ABANDONED_GAME_STATE = 'abandoned'

class GameStateEnum(StrEnum):
    BACKLOG = BACKLOG_GAME_STATE
    IN_PROGRESS = IN_PROGRESS_GAME_STATE
    COMPLETED = COMPLETED_GAME_STATE
    ABANDONED = ABANDONED_GAME_STATE
